<?php

namespace Acme\PasswordCheckerBundle\Entity;

/**
 * PasswordCheckerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordCheckerRepository extends \Doctrine\ORM\EntityRepository
{
}
